# Generated by Django 3.1 on 2020-09-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200907_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='project',
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='commits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.commit'),
        ),
    ]
