# Generated by Django 3.1 on 2020-09-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200907_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='commits',
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commits', to='app.project'),
        ),
    ]
