# Generated by Django 3.1 on 2020-09-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200907_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepost',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
